### PR TITLE
Generate Project.toml and remove REQUIRE 

### PR DESCRIPTION
**Pull request by tknopp**
This is in preparation of the first release.

### CODE REVIEW

**Comment by tknopp** [comment]
@scls19fr @andrewadare: Any objects to merging this and doing the release? I have installed Registrator and just need to trigger the build bot.

**Comment by scls19fr** [comment]
Sorry @tknopp but I can't personally merge this PR (I'm not a JuliaIO member and I haven't write access in JuliaIO/LibSerialPort.jl repository)
but @andrewadare or @samuelpowell can probably do this.

**Comment by tknopp** [comment]
I can so this. Just want that someone is fine with this.

**Comment by scls19fr** [comment]
Oh yes! sorry I read too quickly! LGTM

**Comment by tknopp** [comment]
should we merge #25 prior to the release?

**Comment by scls19fr** [comment]
I think first published release should be done before merging #25

**Comment by tknopp** [comment]
why, what is wrong with #25? The convert thing reads like a clear bugfix to me.

**Comment by scls19fr** [comment]
Hope to you... I prefer to have one more release which will add this "bugfix" (which is more a new "feature" in fact)

**Pull request merged**
