### PR TITLE
Improvements to interface, testing, and examples

### PR DESCRIPTION
**Pull request by andrewadare**
This PR is intended to follow up on work done by @mgkuhn in #56. The scope has grown from a focus on read methods to a package-wide overhaul.
 - The `read` methods defined in high-level-api.jl were mostly removed, allowing io.jl in the Julia Base module to do its job. See #58.
 - A `read_timeout_ms` field was added to the SerialPort type.
 - As done for `write` in #56, the `read` method now calls into `sp_blocking_read` instead of the nonblocking version.
 - The old read behavior is still available as the newly-renamed `nonblocking_read` function. This is likely a breaking change.
 - The "tests" were more like example scripts. Now they actually use `@test`.
 - The read methods introduced in #45 were removed. They did not work and the equivalent functionality is now provided in other ways.
 - A minimal working example script was added to examples/, and is now used as the README example (see #52).

I still haven't fully worked out the timeout logic for the blocking read methods. @mgkuhn provided valuable suggestions in #58, which I have partially implemented. All tests and examples now work on my computer (macOS Catalina) with an Arduino Uno running serial_example.ino.

### CODE REVIEW

**Comment by samuelpowell** [comment]
I know @ianshmean had some particular use cases that were causing him trouble, perhaps it's worthwhile seeing if he has time to comment?

**Comment by mgkuhn** [comment]
Overall the PR looks like a big step in the right direction, thanks!

Note that I just use a [USB serial adapter](https://www.adafruit.com/product/954) with its RX and TX wires directly connected with each other, so just a hardware loopback wire and no Arduino board involved. I suspect that is why the tests still fail for me:
```
Read timeout (ms, forever if 0): 1000

Read all data currently waiting in the serial input buffer...
Wrote test message 1
test message 1
Blocking read/write: Test Failed at /home/mgk25/.julia/dev/LibSerialPort/test/test-high-level-api.jl:21
  Expression: startswith(line, "Received test message")
   Evaluated: startswith("test message 1", "Received test message")
Stacktrace:
 [1] test_blocking_serial_loopback(::SerialPort) at /home/mgk25/.julia/dev/LibSerialPort/test/test-high-level-api.jl:21
 [2] macro expansion at /home/mgk25/.julia/dev/LibSerialPort/test/test-high-level-api.jl:71 [inlined]
 [3] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
 [4] test_high_level_api(::String, ::Vararg{String,N} where N) at /home/mgk25/.julia/dev/LibSerialPort/test/test-high-level-api.jl:71
```
It would be nice if the tests could also be made to work with such a very basic “loopback” wire. At least, `runtests.jl` should print an explanation of what hardware configuration is required for the tests to pass.

Idea: In the absence of a port parameter, `runtests.jl`could also try to send a test byte to all serial ports found, and then use the first one that echoed that byte back for the remaining tests, i.e. auto-detect the loopback needed for testing.

**Comment by andrewadare** [comment]
> It would be nice if the tests could also be made to work with such a very basic “loopback” wire.

Good idea, this is addressed in https://github.com/JuliaIO/LibSerialPort.jl/pull/61/commits/25b2405ca8265b7c3532a2f7e66f78882d59bdab and https://github.com/JuliaIO/LibSerialPort.jl/pull/61/commits/c855eb9e396465e939604087f5348908ff17eb93.

**Comment by mgkuhn** [comment]
More a cosmetic question: in many places like
```
check(ccall((:sp_set_config_bits, libserialport), SPReturn,
            (Config, Cint), config, Cint(bits)))
```
isn't the call of `Cint()` redundant (as already done automatically by `ccall()`)?

**Comment by andrewadare** [comment]
I think I have addressed all review comments received so far. I still haven't implemented anything sophisticated with read timeouts, but I'm not convinced that we need to do anything more than set `SerialPort.read_timeout_ms`. For blocking read calls, the default behavior is to wait forever instead of missing bytes.

All the examples and tests work for me with three different hardware configurations (which are listed atop runtests.jl).

This is unfortunately a fairly big change set. It would not be simple to split up. In the end, some of the biggest problems were in the tests more than the library code under test.

I have not done any Windows testing, so it would be great if anyone could easily do that.

**Comment by wsphillips** [comment]
Hello, I was just about to open a PR for an extra `readuntil` method when I saw the changes here. 

>     * The read methods introduced in #45 were removed. They did not work and the equivalent functionality is now provided in other ways.

What's the proposed alternative for getting the same functionality after the changes made in this PR? Will the user need to roll their own alternative to the Base extension methods of `readuntil()` contained in LibSerialPort.jl? Will the proposed changes allow fall-back methods in Base to fill in for it's absence here?

**Comment by andrewadare** [comment]
Since LibSerialPort.SerialPort is an IO subtype, the readuntil method is provided by Julia's base module (see [here](https://github.com/JuliaLang/julia/blob/c76960224f60ceefd78f3b1d356ccc0035b08e80/base/io.jl#L447)). You should just be able to call e.g. `readuntil(sp, '\n')` to get a line of characters (note that it will block forever by default after this PR). These higher-level methods like readline and readuntil just delegate to byte-level read methods, which *are* provided by this package, and that's all we've found to be necessary.

**Comment by touchft** [comment]
https://github.com/JuliaIO/LibSerialPort.jl/issues/66#issuecomment-655550523

**Comment by touchft** [comment]
I miss the function `readuntil()` in master branch. Can we have it in this branch?

**Comment by mgkuhn** [comment]
The solution to users not understanding that standard methods for the `IO` type also work for the `LibSerialPort.SerialPort` subtype is that `LibSerialPort` should have a `Documenter`-produced manual, and then `docs/src/index.md` should list all the base methods that can usefully be used with `LibSerialPort.SerialPort`, which would cause readers of the documentation to also discover the availability of `readuntil`.

**Comment by mgkuhn** [comment]
In `README.md`:
* please change `name = "/dev/ttyUSB1"` to `portname = "/dev/ttyUSB1"` (as used by the following open)
* review the reference to “support for args in the Pkg REPL” as this feature request appears to already have been implemented last year

If `tests/runtests.jl` is called without any arguments, it should
* print the description of the loopback hardware required to perform the test, which is currently just a comment at the start of the file (simply make that a triple-quoted string literal instead of a comment)
* print instructions on how to actually run a loop-back test
* print a list of serial ports found (e.g. in form of test command lines)
* terminate with success

The loopback tests should *only* be run by `tests/runtests.jl` if a serial port name is explicitly provided as an argument:
* this will remove the need to make running on a CI server a special case
* this removes safety concerns about sending test bytes to a serial port without explicit user consent (test bytes sent to serial ports unintentionally can cause real damage, e.g. recall that the maiden flight of the Ariane 5 rocket blew up after an unhandled exception caused a test dump being sent via a serial port to the motors that rotate the nozels!)
* in particular, please remove the potentially dangerous `port = "/dev/ttyS0"` default from `tests/runtests.jl` (which for all we know might be connected to highly explosive equipment, such as a big rocket motor ;-)
* optional: one could implement a "--scan" argument option that sends one single probe byte (perhaps NUL?) to each port found, and then looks (with say 250 ms timeout) which ports echoed that byte back, then runs the full test on each port that did and therefore appears to have a loopback in place, for the benefit of people who have a test machine with say five serial port adapters (and nothing explosive connected to them) that they all want to test routinely

**Comment by mgkuhn** [comment]
(Apologies for the late response, I'm back now!)

When I run the tests on Ubuntu 18.04, I get many (shortened output)
```
Bytes missing:  UInt8[0x11, 0x13]
┌ Warning: Received data does not match transmitted data:
└ @ Main ~/.julia/dev/LibSerialPort/test/test-low-level-api.jl:59
┌ Warning: Received data does not match transmitted data:
└ @ Main ~/.julia/dev/LibSerialPort/test/test-high-level-api.jl:72
Test Summary:              | Pass  Fail  Total
LibSerialPort              |   68    22     90
  Low level API            |   44    20     64
    Blocking read/write    |   20    10     30
    Nonblocking read/write |    1            1
    Blocking read/write    |   20    10     30
    Nonblocking read/write |    1            1
  High level API           |   24     2     26
    Blocking read/write    |   10           10
    Nonblocking read       |    1            1
    Bytestring roundtrip   |          1      1
    Blocking read/write    |   10           10
    Nonblocking read       |    1            1
    Bytestring roundtrip   |          1      1
ERROR: LoadError: Some tests did not pass: 68 passed, 22 failed, 0 errored, 0 broken.
```

When doing binary tests that include the bytes 0x11 (Ctrl-Q, XON) and 0x13 (Ctrl-S, XOFF), XON/XOFF flow control obviously must be switched off first.

The documentation string for `test_low_level_api()` claims “Hardware and software flow control measures are disabled by
default”. That would seem sensible, but seems currently to be a lie: I can't find any call to `set_flow_control()` to actually disable flow control. I suspect we instead get the operating-system default, which on my machine is
```
$ stty -F /dev/ttyUSB1 -a
[...] ixon -ixoff [...]
```
Could you please explicitly switch off flow control, at least in the tests? It might even be a good idea to make flow-control a default-off parameter of `open()`.

**Comment by touchft** [comment]
Can I make a PR for this branch ama/fix-read-methods ? Based on branch ama/fix-read-methods and master branch, I make a new `readuntil()` and want to add it to branch ama/fix-read-methods.

**Comment by andrewadare** [comment]
What is wrong with the existing readuntil method? It works fine in my tests.

**Comment by mgkuhn** [comment]
@touchft What is wrong with [the existing implementation](https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/base/io.jl#L718-L745) of [Base.readuntil](https://docs.julialang.org/en/v1/base/io-network/#Base.readuntil), which is already working for `SerialPort` because `SerialPort` is a subtype of `IO`, i.e. inherits all methods from `IO`. Why do you think the `SerialPort` type needs a specialization of `Base.readuntil` and what would it do that `Base.readuntil(s::IO, delim::AbstractChar; keep::Bool=false)` doesn't already do?

If this is about timeouts: we are going to implement timeouts in read() and unsafe_read() via an exception and a new timeout parameter inside the `SerialPort` struct, and that new parameter and exception with then just be passed on through `Base.readuntil(s::IO,...)` (and lots of other standard `IO` methods) as well.

**Comment by touchft** [comment]
> What is wrong with the existing readuntil method? It works fine in my tests.

Nothing wrong. Three things I consider for the change are: 
1.the return from `readuntil` (String) is not consistent with the return of `read` (UInt8[...]), I like the later due to binary transport of serial port.
2.lack the control `keep` while `readuntil` in io.jl have this.
3.I want to one more keyword to control the maximum number of bytes read.

Maybe I am too greedy ^-^

Code is here:
```
"""
`readuntil(sp::SerialPort, delim::Vector{UInt8}, timeout_ms::Real; max_read_size::Int = typemax(Int16), keep::Bool = false)`

Read until the specified delimiting byte (e.g. `'\\n'`) is encountered, or until timeout_ms has elapsed, or maximum size of bytes readed, whichever comes first. The delimiter can be a UInt8, AbstractChar, AbstractString, or Vector{UInt8}. Keyword argument keep controls whether the delimiter is included in the result. The text is assumed to be encoded in UTF-8.
"""
function Base.readuntil(sp::SerialPort, delim::Vector{UInt8}, timeout_ms::Real; max_read_size::Int = typemax(Int16), keep::Bool = false)
    read_timeout_ms = sp.read_timeout_ms
    start_time = time_ns()
    read_start_time = start_time
    num_read_bytes = 0
    out = IOBuffer(maxsize=max_read_size)
    find_delim = false
    if length(delim) == 0
        nodelim = true
    else
        nodelim = false
        lastchars = UInt8[0 for i=1:length(delim)]
    end

    while !eof(sp)
        # set read_timeout
        current_time = time_ns()
        if (current_time - read_start_time)/1e6 > read_timeout_ms
            # @info "No data available. Time out!"
            break
        end
        # set total timeout
        if (current_time - start_time)/1e6 > timeout_ms
            # @info "Total time (read) is out."
            break
        end

        # The space in IOBuffer remains for write
        maxbuffer = max_read_size - num_read_bytes
        n = bytesavailable(sp)

        if maxbuffer <= 0
            # @info "Read buffer is full."
            break
        end

        if n > 0
            n = min(maxbuffer, n)
            if nodelim
                c = read(sp,n) # max number of bytes for once read(sp) is: 4095
                write(out, c)
                num_read_bytes += n
            else
                for i in 1:n
                    c = read(sp,1)
                    write(out,c)
                    lastchars = circshift(lastchars,-1)
                    lastchars[end] = c[1] # c isa Vector{UInt8}
                    num_read_bytes += 1
                    if lastchars == delim
                        find_delim=true
                        # println("find delim !")
                        break
                    end
                end
            end
            read_start_time = time_ns()
            find_delim && break
        end
    end
    # @show num_read_bytes
    if find_delim && !keep
        return take!(out)[1:end-size(delim,1)]
    else
        return take!(out)
    end
end

Base.readuntil(sp::SerialPort, delim::Union{AbstractString,AbstractArray{Int,1}}, timeout_ms; max_read_size::Int = typemax(Int16), keep::Bool = false) = Base.readuntil(sp, Vector{UInt8}(delim), timeout_ms; max_read_size = max_read_size, keep=keep)

Base.readuntil(sp::SerialPort, delim::Union{UInt8,AbstractChar}, timeout_ms; max_read_size::Int = typemax(Int16), keep::Bool = false) = Base.readuntil(sp, Vector{UInt8}([delim]), timeout_ms; max_read_size = max_read_size, keep=keep)

Base.readuntil(sp::SerialPort, timeout_ms::Real; max_read_size = typemax(Int16), keep::Bool = false) = Base.readuntil(sp, Vector{UInt8}(), timeout_ms; max_read_size = max_read_size, keep=keep)
```

**Comment by mgkuhn** [comment]
> 1.the return from `readuntil` (String) is not consistent with the return of `read` (UInt8[...]), I like the later due to binary transport of serial port.

The [existing `readuntil(stream::IO, delim; keep::Bool)` method](https://docs.julialang.org/en/v1/base/io-network/#Base.readuntil) from `base/io.jl` accepts both `UInt8` or `Vector{UInt8}` values for `delim`, and in both cases will return Vector{UInt8}:

```
julia> readuntil(stdin, 0x40)
abc@def
3-element Array{UInt8,1}:
 0x61
 0x62
 0x63
julia> readuntil(stdin, UInt8[0x40])
abc@def
3-element Array{UInt8,1}:
 0x61
 0x62
 0x63
```

So no need to “reinvent the wheel” inside this package's high-level API, which is essentially just the serial-port driver for the `IO` system of Base.

> 3.I want to one more keyword to control the maximum number of bytes read.

That sounds like a perfectly reasonable pull request for [base/io.jl](https://github.com/JuliaLang/julia/blob/master/base/io.jl), as there is nothing specific to this feature request for serial ports. The same feature request seems perfectly useful for use with lots of other IO drivers than just this one.

The only other feature of your routine, the timeout, we will be doing in a way that works fine with all the many different readuntil methods in Base.

**Comment by touchft** [comment]
> > 1.the return from `readuntil` (String) is not consistent with the return of `read` (UInt8[...]), I like the later due to binary transport of serial port.
> 
> The [existing `readuntil(stream::IO, delim; keep::Bool)` method](https://docs.julialang.org/en/v1/base/io-network/#Base.readuntil) from `base/io.jl` accepts both `UInt8` or `Vector{UInt8}` values for `delim`, and in both cases will return Vector{UInt8}:
> 
> ```
> julia> readuntil(stdin, 0x40)
> abc@def
> 3-element Array{UInt8,1}:
>  0x61
>  0x62
>  0x63
> julia> readuntil(stdin, UInt8[0x40])
> abc@def
> 3-element Array{UInt8,1}:
>  0x61
>  0x62
>  0x63
> ```
> 
> So no need to “reinvent the wheel” inside this package's high-level API, which is essentially just the serial-port driver for the `IO` system of Base.
> 
> > 3.I want to one more keyword to control the maximum number of bytes read.
> 
> That sounds like a perfectly reasonable pull request for [base/io.jl](https://github.com/JuliaLang/julia/blob/master/base/io.jl), as there is nothing specific to this feature request for `SerialPort`. The same feature request seems perfectly useful for use with lots of other IO drivers than just this one.
> 
> The only other feature of your routine, the timeout, we will be doing in a way that works fine with all the many different readuntil methods in Base.

Great! I think I miss checking the master branch of LibSerialPort.jl (I checked the Julia repo and branch ama/fix-read-method ). I found that one useful blocking read method is missing in the master and ama/fix-read-method branch, i.e, "readavailable(::SerialPort)".

In branch: ama/fix-read-method: 
The nonblock read method "nonblocking_read(sp::SerialPort)" seems results no difference with methd "read(sp::SerialPort)".

**Pull request merged**
