### PR TITLE
Test moving to libserialport_jll dependency

### PR DESCRIPTION
**Pull request by ianshmean**
Requires julia 1.3+, and expands libserialport deps out to all the binarybuilder platforms. Shouldn't be merged until 1.3 is released

On my linux machine actually get [test errors on master](https://github.com/JuliaIO/LibSerialPort.jl/issues/42), seemingly connected to permissions, with 50% passing, but I get the same errors on this PR.. 

All tests pass on my mac.

~~Note.. I made an error in the first libserialport_jll release, leaving in a const from libnettle. It will be fixed in the next release https://github.com/JuliaPackaging/Yggdrasil/pull/191~~ Fixed

### CODE REVIEW

**Comment by ianshmean** [comment]
I don't know how indicative the package tests are, but I've expanded the travis testing, based on discourse posts on [Windows](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187) and [ARM](https://discourse.julialang.org/t/julia-aarch64-builds-are-now-available-on-travis-ci/29970), and [this](https://github.com/ararslan/Jackknife.jl/blob/231f924f9da3184c2ae360484368c7ef55e0a612/.travis.yml) config. 

Thought I'm not sure why travis failed to exclude the excluded jobs..

**Comment by ianshmean** [comment]
The windows error is https://github.com/JuliaLang/julia/pull/33592

The arm error: I'm looking into how to chmod on ARM travis images

**Comment by ianshmean** [comment]
ARM CI is fixed. The only failure is a problem with 1.3-rc4. This can be considered ready for when 1.3 lands

**Comment by andrewadare** [comment]
@ianshmean thanks for this PR. I have looked over the diffs, but am currently traveling and not able to run tests. Since this is intended for Julia 1.3, I assume it's not a problem if I pick this up next week. Thanks again! Very nice simplifications to the build setup.

**Comment by samuelpowell** [comment]
@ianshmean great idea, I am also saturated at the moment but would be pleased to take a look when 1.3 lands. Can you ping when the time is right?

**Comment by yakir12** [comment]
I might be testing this in the wild in the next few days. Will report back if it passes. Thanks!

**Comment by ianshmean** [comment]
I just wanted to check if anyone had had a chance to try this out?

**Comment by yakir12** [comment]
I'm doing field work right now and one of the users' computer (mac) needs this, but since she we managed avoiding the problem (by temporarily using someone else's computer) we won't be trying things out before returning home so as not to risk anything here (also to save on time).

**Comment by andrewadare** [comment]
I just downloaded 1.3.0-rc5.1 and got your PR via `(v1.3) pkg> add LibSerialPort#jll`. I'll test tonight when I can plug in a device and report back.

**Comment by andrewadare** [comment]
Both the low level and high level API tests work as expected on my system. Looks good!

**Comment by yakir12** [comment]
I tried this on a Mojave 10.14.3 and it works, both the tests but also my own code. Fantastic work!

**Comment by ianshmean** [comment]
Great.  1.3 has now been released, so this can be merged

**Comment by ianshmean** [comment]
@samuelpowell Let me know if you can test soon, otherwise I'll go ahead and merge & release a new minor version

**Comment by samuelpowell** [comment]
@ianshmean I confirm it installs and loads nicely but I won't be able to do any hardware testing for a couple of weeks, so don't wait on me!

**Comment by samuelpowell** [comment]
(though you do seem to have test failure on CI)

**Comment by ianshmean** [comment]
The failure on 32-bit windows was a `julia-1.3.0-rc4.1` specific issue. I've rerun that job and it's all green ticks now 

@samuelpowell probably worth disabling appveyor now, which is under your appveyor user account

**Pull request merged**
