### PR TITLE
Move Windows binary repository to JuliaIO

### PR DESCRIPTION
**Pull request by samuelpowell**
Part of https://github.com/JuliaIO/Roadmap/issues/3

### CODE REVIEW

**Comment by samuelpowell** [comment]
@ReubenHill could you check this branch correctly builds and runs on Windows?

**Comment by ReubenHill** [comment]
Builds OK windows 64 bit but tests do not work - it looks like they are only written for Linux/MacOS. I note that CI only targets those platforms too. Looks like some work needs to be done to get this working for windows again...

```
julia> using LibSerialPort

julia> list_ports()
OS error code 0: The operation completed successfully.
ERROR: From C:\Users\Reuben\Documents\GitHub\LibSerialPort.jl\src\wrap.jl: 141:

libserialport returned SP_ERR_FAIL - Host OS reported a failure.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] handle_error(::SPReturn, ::String) at C:\Users\Reuben\Documents\GitHub\LibSerialPort.jl\src\wrap.jl:136
 [3] sp_list_ports at C:\Users\Reuben\Documents\GitHub\LibSerialPort.jl\src\wrap.jl:164 [inlined]
 [4] #list_ports#29(::Int64, ::Function) at C:\Users\Reuben\Documents\GitHub\LibSerialPort.jl\src\high-level-api.jl:114
 [5] list_ports() at C:\Users\Reuben\Documents\GitHub\LibSerialPort.jl\src\high-level-api.jl:114
 [6] top-level scope at none:0
```

**Comment by samuelpowell** [comment]
Thanks, I don't think that ever worked. Can you open a port directly by name?

**Comment by ReubenHill** [comment]
Yes: it works. It turns out that error was for no serial ports being present.

```
julia> using LibSerialPort

julia> list_ports()
COM4
        Description:    USB Serial Port (COM4)
        Transport type: SP_TRANSPORT_USB

julia> port = SerialPort("COM4")
SerialPort(Ptr{LibSerialPort.SPPort} @0x000000000b1cb870, false, false)
```

**Comment by samuelpowell** [comment]
Great, thanks for your help @ReubenHill. Merging.

**Pull request merged**
