### PR TITLE
Add readline and readuntil with timeout

### PR DESCRIPTION
**Pull request by ianshmean**
`readline` and `readuntil`, but with timeouts, to help avoid hanging with uncertain serial connections.

This PR is based on #43, so that should be merged first (and this may need rebasing when that happens).

```julia
LibSerialPort.open(port, 115200) do s
    write(s, "input")
    ret = readline(s, 1.0) #try to readline with a 1 second timeout
    @show ret
end
```

```julia
LibSerialPort.open(port, 115200) do s
    write(s, "input")
    ret = readuntil(s, 'x', 1.0) #try to readuntil char `x` with a 1 second timeout
    @show ret
end
```

### CODE REVIEW

**Comment by ianshmean** [comment]
What are your thoughts on adding these? The base io reading methods aren't particularly serial-friendly, given the tendency for serial comms to be iffy.

Doesn't change anything, just adds methods, so could be a minor version bump (and all tests pass)

cc. @andrewadare @samuelpowell @yakir12

**Comment by yakir12** [comment]
Love it!

**Comment by ianshmean** [comment]
I'll merge if I get a second thumbs up :)

**Comment by andrewadare** [comment]
Ahh, missed my window...I was in the middle of commenting.

I was going to
(a) say that I tested this with a microcontroller, and the new methods work great (although I did not try adding delays on the MCU side to simulate a flaky connection
(b) note that this new `readuntil` serves basically the same purpose as the existing [method](https://github.com/JuliaIO/LibSerialPort.jl/blob/e69636de769f625c7a50ff2c4fbdfa89ba7c84a6/src/high-level-api.jl#L394), but this implementation is better.

When I created this package about four years ago, I had copied `Base.readuntil` and modified it where needed. But it looks the Julia Base implementations look quite different from what I remember (which is hardly surprising). 

This suggests to me that we may want to get rid of my original method in favor of the newly merged one. For one thing, there's now an API inconsistency because the new timeouts are in seconds and I chose to use milliseconds.

**Comment by ianshmean** [comment]
oh, that's embarrassing.. I totally missed those existing methods!! Sorry @andrewadare
I'll also wait for your review for any further changes (got carried away) 

I don't know how that happened.. perhaps because I scanned the exported functions in LibSerialPort.jl, while `readuntil` wasn't there given it's implicitly exported due to the base import.

I've [blocked the latest release](https://github.com/JuliaRegistries/General/pull/5939) (after the jll one), so we can discuss

Sorry for the mixup! I'll let you decide how to proceed

**Comment by andrewadare** [comment]
No worries at all, these changes are an improvement, and I think we should bring them in. The new methods use more modern syntax and better logic.

In retrospect, defining those methods under the `Base` namespace in this package was kind of an anti-pattern because of the lack of transparency. I doubt I'd do that again without good reason.

This is slightly tricky, because the new `readuntil` method has the same signature apart from the keyword arg, but replacing with this PR would be a breaking change because of the ms vs. seconds issue. So we could change your timeout to milliseconds or bump the MAJOR semver from 0 -> 1. Thoughts? I'm fine with either.

**Comment by ianshmean** [comment]
Happy to move to ms and avoid the break. 
Obviously the readme would need updating.

**Comment by yakir12** [comment]
Similarly to VideoIO, why not use some `<: TimePeriod`? That would remove this ambiguity about seconds or milliseconds. That's why we have Dates as a standard library. Why not make use of it?

And as a side comment, I use my small [COBS](https://github.com/yakir12/COBS.jl) library to solve the "read until" problem (framing problem, termination problem). I am sure my package could improve (mainly in speed, but maybe also in terms of edge cases), but, yea, just wanted to highlight it in case it can make a different in terms of the `readuntil` function.

**Pull request merged**
